
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BENDEW BRO_SAY ENDINSTR HELP IDK IM_A_HACKER IM_BATMAN I_HATE_THIS_LANG LICENSE NUM PLS_ADD PLS_SUB SHEEEEEEEESH STR SUUUUUUUUUUU WHAT_IS_IT YAY YES ZIGOTOstatement : expression ENDINSTR\n                 | print ENDINSTR\n                 | zigoto ENDINSTR\n                 | bendew ENDINSTR\n                 | what_is_it ENDINSTR\n                 | shesh ENDINSTR\n                 | yes ENDINSTR\n                 | im_a_hacker ENDINSTR\n                 | suuu ENDINSTR\n                 | help ENDINSTR\n                 | license ENDINSTR\n                 | i_hate_this_lang ENDINSTRexpression : expression PLS_ADD expression\n                  | expression PLS_SUB expression\n                  | expression IM_BATMAN expression\n                  | expression YAY expression\n                  | NUMprint : BRO_SAY STRzigoto : ZIGOTObendew : BENDEWwhat_is_it : WHAT_IS_ITshesh : SHEEEEEEEESHyes : YESim_a_hacker : IM_A_HACKERsuuu : SUUUUUUUUUUUhelp : HELPlicense : LICENSEi_hate_this_lang : I_HATE_THIS_LANG'
    
_lr_action_items = {'NUM':([0,27,28,29,30,],[14,14,14,14,14,]),'BRO_SAY':([0,],[15,]),'ZIGOTO':([0,],[16,]),'BENDEW':([0,],[17,]),'WHAT_IS_IT':([0,],[18,]),'SHEEEEEEEESH':([0,],[19,]),'YES':([0,],[20,]),'IM_A_HACKER':([0,],[21,]),'SUUUUUUUUUUU':([0,],[22,]),'HELP':([0,],[23,]),'LICENSE':([0,],[24,]),'I_HATE_THIS_LANG':([0,],[25,]),'$end':([1,26,31,32,33,34,35,36,37,38,39,40,41,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,]),'ENDINSTR':([2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,42,43,44,45,46,],[26,31,32,33,34,35,36,37,38,39,40,41,-17,-19,-20,-21,-22,-23,-24,-25,-26,-27,-28,-18,-13,-14,-15,-16,]),'PLS_ADD':([2,14,43,44,45,46,],[27,-17,27,27,27,27,]),'PLS_SUB':([2,14,43,44,45,46,],[28,-17,28,28,28,28,]),'IM_BATMAN':([2,14,43,44,45,46,],[29,-17,29,29,29,29,]),'YAY':([2,14,43,44,45,46,],[30,-17,30,30,30,30,]),'STR':([15,],[42,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,27,28,29,30,],[2,43,44,45,46,]),'print':([0,],[3,]),'zigoto':([0,],[4,]),'bendew':([0,],[5,]),'what_is_it':([0,],[6,]),'shesh':([0,],[7,]),'yes':([0,],[8,]),'im_a_hacker':([0,],[9,]),'suuu':([0,],[10,]),'help':([0,],[11,]),'license':([0,],[12,]),'i_hate_this_lang':([0,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression ENDINSTR','statement',2,'p_statement','parser.py',30),
  ('statement -> print ENDINSTR','statement',2,'p_statement','parser.py',31),
  ('statement -> zigoto ENDINSTR','statement',2,'p_statement','parser.py',32),
  ('statement -> bendew ENDINSTR','statement',2,'p_statement','parser.py',33),
  ('statement -> what_is_it ENDINSTR','statement',2,'p_statement','parser.py',34),
  ('statement -> shesh ENDINSTR','statement',2,'p_statement','parser.py',35),
  ('statement -> yes ENDINSTR','statement',2,'p_statement','parser.py',36),
  ('statement -> im_a_hacker ENDINSTR','statement',2,'p_statement','parser.py',37),
  ('statement -> suuu ENDINSTR','statement',2,'p_statement','parser.py',38),
  ('statement -> help ENDINSTR','statement',2,'p_statement','parser.py',39),
  ('statement -> license ENDINSTR','statement',2,'p_statement','parser.py',40),
  ('statement -> i_hate_this_lang ENDINSTR','statement',2,'p_statement','parser.py',41),
  ('expression -> expression PLS_ADD expression','expression',3,'p_expression','parser.py',45),
  ('expression -> expression PLS_SUB expression','expression',3,'p_expression','parser.py',46),
  ('expression -> expression IM_BATMAN expression','expression',3,'p_expression','parser.py',47),
  ('expression -> expression YAY expression','expression',3,'p_expression','parser.py',48),
  ('expression -> NUM','expression',1,'p_expression','parser.py',49),
  ('print -> BRO_SAY STR','print',2,'p_print','parser.py',66),
  ('zigoto -> ZIGOTO','zigoto',1,'p_zigoto','parser.py',70),
  ('bendew -> BENDEW','bendew',1,'p_bendew','parser.py',85),
  ('what_is_it -> WHAT_IS_IT','what_is_it',1,'p_what_is_it','parser.py',89),
  ('shesh -> SHEEEEEEEESH','shesh',1,'p_shesh','parser.py',93),
  ('yes -> YES','yes',1,'p_yes','parser.py',97),
  ('im_a_hacker -> IM_A_HACKER','im_a_hacker',1,'p_im_a_hacker','parser.py',101),
  ('suuu -> SUUUUUUUUUUU','suuu',1,'p_suuu','parser.py',105),
  ('help -> HELP','help',1,'p_help','parser.py',109),
  ('license -> LICENSE','license',1,'p_license','parser.py',113),
  ('i_hate_this_lang -> I_HATE_THIS_LANG','i_hate_this_lang',1,'p_i_hate_this_lang','parser.py',140),
]
